dist: focal

language: cpp

git:
  depth: 1
  
addons:
  snaps: 
  - name: dotnet-sdk
    confinement: classic
    channel: latest

compiler: g++

before_install:
  - sudo apt-get update
  - sudo apt-get install libssl-dev
  - sudo apt-get install libpq-dev

script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - cd Server
  - mkdir Build
  - chmod u+rx BUILD
  - ./BUILD
  - cd ../Client.Logic
  - dotnet build Client.Logic.csproj
