dist: bionic

language: cpp

git:
  depth: 1

compiler: g++

before_install:
  - sudo apt-get update
  - sudo apt-get install libssl-dev
  - sudo apt-get install libpq-dev

script:
  - cd Server
  - mkdir Build
  - chmod u+rx BUILD
  - ./BUILD
