language: cpp

git:
  depth: 1

branches:
  only:
    - master

compiler:
  - g++

before_install:
  - sudo apt-get update
  - sudo apt-get install libsqlite3-dev
  - sudo apt-get install libssl-dev
  - sudo apt-get install gcc-7.1 g++-7.1
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7.1 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7.1 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++

script:
  - cd Server
  - mkdir Build
  - chmod u+rx BUILD
  - ./BUILD
