language: cpp

git:
  depth: 1

branches:
  only:
    - master

compiler:
  - gcc

before_install:
  - sudo apt-get install sqlite3 libsqlite3-dev
  - sudo apt-get install libssl-dev
  
script:
  - Server/Build
