#pragma once

enum AttackResult
{
    ATTACK_RESULT_INVALID_TARGET = 0,
    ATTACK_RESULT_CARD_ATTACKED,
    ATTACK_RESULT_CARD_DESTROYED
};

enum StatStystem
{
    DEFENSE_PERCENT_PER_POINT   = 6,
    DEFENSE_BONUS_ON_DEFEND     = 2,
    MANA_REPLENISHMENT_MOVES    = 15,
    MANA_REPLENISHMENT_VALUE    = 2
};
