#pragma once
#include  <cstdint>

enum SpellAuraEffects : uint8_t
{
    SPELL_AURA_EFFECT_DAMAGE = 0,
    SPELL_AURA_EFFECT_MODIFY_STAT,
    SPELL_AURA_EFFECT_HEAL,
    SPELL_AURA_EFFECT_MORPH,
    MAX_SPELL_AURA_VALUE
};

enum SpellAttributes : uint8_t
{
    SPELL_ATTRIBUTE_TARGET_MELEE        = 0x01,
    SPELL_ATTRIBUTE_TARGET_EXCLUDE_SELF = 0x02,
    SPELL_ATTRIBUTE_APPLY_DEFENSE       = 0x04,
    SPELL_ATTRIBUTE_AURA_EXCLUSIVE      = 0x08,
    SPELL_ATTRIBUTE_CONTINUE_MOVE       = 0x10
};

enum class SpellCastResult : uint8_t
{
    SPELL_CAST_RESULT_SUCCESS = 0,
    SPELL_CAST_RESULT_SUCCESS_CONTINUE_MOVE,
    SPELL_CAST_RESULT_FAIL_CANT_CAST_SPELLS,
    SPELL_CAST_RESULT_FAIL_NOT_ENOUGH_MANA,
    SPELL_CAST_RESULT_FAIL_INVALID_TARGET
};

enum SpellTargets : uint8_t
{
    TARGET_UNIT_TARGET_ENEMY = 0,
    TARGET_UNIT_TARGET_FRIEND,
    TARGET_UNIT_CLEAVE_ENEMY,
    TARGET_UNIT_SELF,
    MAX_SPELL_EFFECT_TARGET
};

