//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Logic.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now aflicted by an effect from {1}.
        /// </summary>
        public static string AuraApplied {
            get {
                return ResourceManager.GetString("AuraApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect of {0} has expired from {1}.
        /// </summary>
        public static string AuraExpired {
            get {
                return ResourceManager.GetString("AuraExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been demorphed from {1}.
        /// </summary>
        public static string CardDemorph {
            get {
                return ResourceManager.GetString("CardDemorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been healed by {1}.
        /// </summary>
        public static string CardHealed {
            get {
                return ResourceManager.GetString("CardHealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has killed {1} with {2} damage.
        /// </summary>
        public static string CardKilled {
            get {
                return ResourceManager.GetString("CardKilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  has been morphed to {1}.
        /// </summary>
        public static string CardMorphed {
            get {
                return ResourceManager.GetString("CardMorphed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been killed with {1} damage.
        /// </summary>
        public static string CardPeriodicKill {
            get {
                return ResourceManager.GetString("CardPeriodicKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage.
        /// </summary>
        public static string Damage {
            get {
                return ResourceManager.GetString("Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string Defense {
            get {
                return ResourceManager.GetString("Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in use.
        /// </summary>
        public static string EmailInUse {
            get {
                return ResourceManager.GetString("EmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card count.
        /// </summary>
        public static string InvalidCardCount {
            get {
                return ResourceManager.GetString("InvalidCardCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server does not support every card you&apos;ve selected.
        /// </summary>
        public static string InvalidCardId {
            get {
                return ResourceManager.GetString("InvalidCardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot attack that target.
        /// </summary>
        public static string InvalidTarget {
            get {
                return ResourceManager.GetString("InvalidTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string Mana {
            get {
                return ResourceManager.GetString("Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} consumes {1} mana from {2}.
        /// </summary>
        public static string ManaConsume {
            get {
                return ResourceManager.GetString("ManaConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Cards have replenished {1} mana.
        /// </summary>
        public static string ManaReplenished {
            get {
                return ResourceManager.GetString("ManaReplenished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} has disconnected.
        /// </summary>
        public static string PlayerDisconnected {
            get {
                return ResourceManager.GetString("PlayerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has joined the game.
        /// </summary>
        public static string PlayerJoinedGame {
            get {
                return ResourceManager.GetString("PlayerJoinedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player {0} not found.
        /// </summary>
        public static string PlayerNotFound {
            get {
                return ResourceManager.GetString("PlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting cards failed: {0}.
        /// </summary>
        public static string SelectCardsFailed {
            get {
                return ResourceManager.GetString("SelectCardsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} has been changed by {2}.
        /// </summary>
        public static string StatChanged {
            get {
                return ResourceManager.GetString("StatChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error occurred.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already in use.
        /// </summary>
        public static string UsernameInUse {
            get {
                return ResourceManager.GetString("UsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for another player to join the game.
        /// </summary>
        public static string WaitingForPlayer {
            get {
                return ResourceManager.GetString("WaitingForPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for the second player to pick his cards.
        /// </summary>
        public static string WaitingForSecondPlayer {
            get {
                return ResourceManager.GetString("WaitingForSecondPlayer", resourceCulture);
            }
        }
    }
}
