CREATE EXTENSION IF NOT EXISTS CITEXT WITH SCHEMA public;
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email CITEXT UNIQUE NOT NULL,
    user_name CITEXT UNIQUE NOT NULL,
    password_salt CHAR(64) NOT NULL,
    password_hash CHAR(64) NOT NULL,
    user_role SMALLINT NOT NULL,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN NOT NULL
);
