name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: create output
      working-directory: ./Server
      run: mkdir output
    - name: setup permissions
      working-directory: ./Server
      run: chmod u+rx BUILD
    - name: build project
      working-directory: ./Server
      run: ./BUILD
